Updated to v2.9.6.1

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3136,7 +3136,7 @@ fi
 # Define the identity of the package.
 
  PACKAGE=snort
- VERSION=2.9.6.0
+ VERSION=2.9.6.1
 
 
 cat >>confdefs.h <<_ACEOF
@@ -15528,6 +15528,60 @@ fi
     if test "x$LDAQ" = "xno"; then
         echo
         echo "   ERROR!  daq library not found, go get it from"
+        echo "   http://www.snort.org/."
+        #AC_MSG_ERROR("Fatal!")
+        exit 1
+    fi
+fi
+
+if test "x$enable_control_socket" = "xyes"; then
+    LSFBPF=""
+    { $as_echo "$as_me:${as_lineno-$LINENO}: checking for pcap_dump in -lsfbpf" >&5
+$as_echo_n "checking for pcap_dump in -lsfbpf... " >&6; }
+if ${ac_cv_lib_sfbpf_pcap_dump+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lsfbpf   $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char pcap_dump ();
+int
+main ()
+{
+return pcap_dump ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  ac_cv_lib_sfbpf_pcap_dump=yes
+else
+  ac_cv_lib_sfbpf_pcap_dump=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_sfbpf_pcap_dump" >&5
+$as_echo "$ac_cv_lib_sfbpf_pcap_dump" >&6; }
+if test "x$ac_cv_lib_sfbpf_pcap_dump" = xyes; then :
+  LIBS="${LIBS} -lsfbpf"
+else
+  LSFBPF="no"
+fi
+
+
+    if test "x$LSFBPF" = "xno"; then
+        echo
+        echo "   ERROR!  sfbpf library not found, go get it from"
         echo "   http://www.snort.org/."
         #AC_MSG_ERROR("Fatal!")
         exit 1
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -6,7 +6,7 @@ AC_PREREQ(2.50)
 AM_CONFIG_HEADER(config.h)
 # When changing the snort version, please also update the VERSION
 # definition in "src/win32/WIN32-Includes/config.h"
-AM_INIT_AUTOMAKE(snort,2.9.6.0)
+AM_INIT_AUTOMAKE(snort,2.9.6.1)
 
 NO_OPTIMIZE="no"
 ADD_WERROR="no"
@@ -692,6 +692,20 @@ else
     if test "x$LDAQ" = "xno"; then
         echo
         echo "   ERROR!  daq library not found, go get it from"
+        echo "   http://www.snort.org/."
+        #AC_MSG_ERROR("Fatal!")
+        exit 1
+    fi
+fi
+
+if test "x$enable_control_socket" = "xyes"; then
+    LSFBPF=""
+    AC_CHECK_LIB([sfbpf], [pcap_dump],
+        [LIBS="${LIBS} -lsfbpf"], [LSFBPF="no"], [ ])
+
+    if test "x$LSFBPF" = "xno"; then
+        echo
+        echo "   ERROR!  sfbpf library not found, go get it from"
         echo "   http://www.snort.org/."
         #AC_MSG_ERROR("Fatal!")
         exit 1
