Updated to snort 2.9.7.0

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -6,7 +6,7 @@ AC_PREREQ(2.50)
 AM_CONFIG_HEADER(config.h)
 # When changing the snort version, please also update the VERSION
 # definition in "src/win32/WIN32-Includes/config.h"
-AM_INIT_AUTOMAKE(snort,2.9.6.2)
+AM_INIT_AUTOMAKE(snort,2.9.7.0)
 
 NO_OPTIMIZE="no"
 ADD_WERROR="no"
@@ -31,6 +31,7 @@ AC_C_INLINE
 #AC_CANONICAL_HOST
 linux="no"
 sunos4="no"
+macos="no"
 so_with_static_lib="yes"
 
 case "$host" in
@@ -109,6 +110,7 @@ case "$host" in
     ;;
 # it is actually <platform>-apple-darwin1.2 or <platform>-apple-rhapsody5.x but lets stick with this for the moment
   *-apple*)
+    macos="yes"
     AC_DEFINE([MACOS],[1],[Define if MacOS])
     AC_DEFINE([BROKEN_SIOCGIFMTU],[1],[Define if broken SIOCGIFMTU])
 esac
@@ -364,6 +366,37 @@ if test "x$with_libpfring_libraries" != "xno"; then
    LDFLAGS="${LDFLAGS} -L${with_libpfring_libraries}"
 fi
 
+AC_ARG_WITH(daq_includes,
+	[  --with-daq-includes=DIR        DAQ include directory],
+	[with_daq_includes="$withval"],[with_daq_includes="no"])
+
+AC_ARG_WITH(daq_libraries,
+	[  --with-daq-libraries=DIR       DAQ library directory],
+	[with_daq_libraries="$withval"],[with_daq_libraries="no"])
+
+if test "x$with_daq_includes" != "xno"; then
+   CPPFLAGS="${CPPFLAGS} -I${with_daq_includes}"
+   ICONFIGFLAGS="${ICONFIGFLAGS} -I${with_daq_includes}"
+fi
+
+if test "x$with_daq_libraries" != "xno"; then
+   LDFLAGS="${LDFLAGS} -L${with_daq_libraries}"
+fi
+
+if test "x$enable_control_socket" = "xyes"; then
+    LSFBPF=""
+    AC_CHECK_LIB([sfbpf], [sfbpf_compile],
+        [LIBS="${LIBS} -lsfbpf"], [LSFBPF="no"], [ ])
+
+    if test "x$LSFBPF" = "xno"; then
+        echo
+        echo "   ERROR!  sfbpf library not found, go get it from"
+        echo "   http://www.snort.org/."
+        #AC_MSG_ERROR("Fatal!")
+        exit 1
+    fi
+fi
+
 LPCAP=""
 AC_CHECK_LIB(pcap, pcap_datalink,, LPCAP="no")
 
@@ -529,14 +562,12 @@ if test "x$with_openssl_libraries" != "xno"; then
     LDFLAGS="${LDFLAGS}  -L${with_openssl_libraries}"
 fi
 # Verify that we have the headers
-SHA_H=""
-OPENSSL_SHA_L=""
-AC_CHECK_HEADERS([openssl/sha.h],, SHA_H="no")
-if test "x$SHA_H" != "xno"; then
-    AC_CHECK_LIB(crypto, [SHA256_Init],, OPENSSL_SHA_L="no")
-    if test "x$OPENSSL_SHA_L" != "xno"; then
-        AC_DEFINE([HAVE_OPENSSL_SHA],[1], [openssl SHA available])
-    fi
+AC_CHECK_LIB([crypto],[SHA256_Init],AC_DEFINE([HAVE_OPENSSL_SHA],[1],openssl SHA available),)
+AC_CHECK_LIB([crypto],[MD5_Init],AC_DEFINE([HAVE_OPENSSL_MD5],[1],openssl MD5 available),)
+AM_CONDITIONAL([BUILD_OPENSSL_MD5], test "$ac_cv_lib_crypto_MD5_Init" != "yes" )
+AM_CONDITIONAL([BUILD_OPENSSL_SHA], test "$ac_cv_lib_crypto_SHA256_Init" != "yes" )
+if test "$ac_cv_lib_crypto_MD5_Init" = "yes"; then
+    LIBS="${LIBS} -lcrypto"
 fi
 
 AC_ARG_VAR(SIGNAL_SNORT_RELOAD, set the SIGNAL_SNORT_RELOAD value)
@@ -635,23 +666,6 @@ if test "x$DNET" = "xno" -a "x$DUMBNET" = "xno"; then
     exit
 fi
 
-AC_ARG_WITH(daq_includes,
-	[  --with-daq-includes=DIR        DAQ include directory],
-	[with_daq_includes="$withval"],[with_daq_includes="no"])
-
-AC_ARG_WITH(daq_libraries,
-	[  --with-daq-libraries=DIR       DAQ library directory],
-	[with_daq_libraries="$withval"],[with_daq_libraries="no"])
-
-if test "x$with_daq_includes" != "xno"; then
-   CPPFLAGS="${CPPFLAGS} -I${with_daq_includes}"
-   ICONFIGFLAGS="${ICONFIGFLAGS} -I${with_daq_includes}"
-fi
-
-if test "x$with_daq_libraries" != "xno"; then
-   LDFLAGS="${LDFLAGS} -L${with_daq_libraries}"
-fi
-
 AC_ARG_ENABLE(static_daq,
 [  --disable-static-daq     Link static DAQ modules.],
        enable_static_daq="$enableval", enable_static_daq="yes")
@@ -698,21 +712,20 @@ else
     fi
 fi
 
-if test "x$enable_control_socket" = "xyes"; then
-    LSFBPF=""
-    AC_CHECK_LIB([sfbpf], [pcap_dump],
-        [LIBS="${LIBS} -lsfbpf"], [LSFBPF="no"], [ ])
+AC_CHECK_FUNCS([daq_hup_apply] [daq_acquire_with_meta] [daq_dp_add_dc])
 
-    if test "x$LSFBPF" = "xno"; then
+if test "x$ac_cv_func_daq_dp_add_dc" = "xyes"; then
+
+    AC_CHECK_MEMBER([struct _DAQ_DP_key_t.sa.src_ip4],[],[DAQ_C99_STRUCT="no"],[#include <daq_common.h>])
+    
+    if test "x$DAQ_C99_STRUCT" = "xno" ; then
         echo
-        echo "   ERROR!  sfbpf library not found, go get it from"
+        echo "   ERROR!  daq library missing C99 patch, upgrade to >=2.0.4, go get it from"
         echo "   http://www.snort.org/."
-        #AC_MSG_ERROR("Fatal!")
         exit 1
     fi
-fi
 
-AC_CHECK_FUNCS([daq_hup_apply] [daq_acquire_with_meta])
+fi
 
 AC_MSG_CHECKING([for daq address space ID])
 AC_RUN_IFELSE(
@@ -730,6 +743,42 @@ AC_MSG_RESULT($have_daq_address_space_id)
 if test "x$have_daq_address_space_id" = "xyes"; then
     AC_DEFINE([HAVE_DAQ_ADDRESS_SPACE_ID],[1],
         [DAQ version supports address space ID in header.])
+fi
+
+AC_MSG_CHECKING([for daq flow ID])
+AC_RUN_IFELSE(
+[AC_LANG_PROGRAM(
+[[
+#include <daq.h>
+]],
+[[
+   DAQ_PktHdr_t hdr;
+   hdr.flow_id = 0;
+]])],
+[have_daq_flow_id="yes"],
+[have_daq_flow_id="no"])
+AC_MSG_RESULT($have_daq_flow_id)
+if test "x$have_daq_flow_id" = "xyes"; then
+    AC_DEFINE([HAVE_DAQ_FLOW_ID],[1],
+        [DAQ version supports flow ID in header.])
+fi
+
+AC_MSG_CHECKING([for DAQ_VERDICT_RETRY])
+AC_RUN_IFELSE(
+[AC_LANG_PROGRAM(
+[[
+#include <daq.h>
+]],
+[[
+   DAQ_Verdict verdict;
+   verdict = DAQ_VERDICT_RETRY;
+]])],
+[have_daq_verdict_retry="yes"],
+[have_daq_verdict_retry="no"])
+AC_MSG_RESULT($have_daq_verdict_retry)
+if test "x$have_daq_verdict_retry" = "xyes"; then
+    AC_DEFINE([HAVE_DAQ_VERDICT_RETRY],[1],
+        [DAQ version supports DAQ_VERDICT_RETRY in DAQ_Verdict.])
 fi
 
 # any sparc platform has to have this one defined.
@@ -809,30 +858,60 @@ if test "x$enable_dlclose" = "xno"; then
     AC_DEFINE([DISABLE_DLCLOSE_FOR_VALGRIND_TESTING],[1],[Don't close opened shared objects for valgrind leak testing of dynamic libraries])
 fi
 
-AC_ARG_ENABLE(zlib,
-[  --disable-zlib           Disable Http Response Decompression],
-       enable_zlib="$enableval", enable_zlib="yes")
-AM_CONDITIONAL(HAVE_ZLIB, test "x$enable_zlib" = "xyes")
-if test "x$enable_zlib" = "xyes"; then
-    Z_LIB=""
-    AC_CHECK_HEADERS(zlib.h,, Z_LIB="no")
-    if test "x$Z_LIB" = "xno"; then
-        echo
-        echo "   ERROR!  zlib header not found, go get it from"
-        echo "   http://www.zlib.net"
-        exit
+Z_LIB=""
+AC_CHECK_HEADERS(zlib.h,, Z_LIB="no")
+if test "x$Z_LIB" = "xno"; then
+    echo
+    echo "   ERROR!  zlib header not found, go get it from"
+    echo "   http://www.zlib.net"
+    exit
+fi
+
+Z_LIB=""
+AC_CHECK_LIB(z, inflate,, Z_LIB="no")
+if test "x$Z_LIB" = "xno"; then
+    echo
+    echo "   ERROR!  zlib library not found, go get it from"
+    echo "   http://www.zlib.net"
+     exit
+ fi
+LIBS="$LIBS -lz"
+
+AC_ARG_ENABLE(lzma,
+[  --disable-lzma           Disable LZMA Decompression],
+       enable_lzma="$enableval", enable_lzma="yes")
+
+AC_ARG_WITH(lzma_includes,
+    [  --with-lzma-includes=DIR       liblzma include directory],
+    [with_lzma_includes="$withval"],[with_lzma_includes="no"])
+
+AC_ARG_WITH(lzma_libraries,
+    [  --with-lzma-libraries=DIR      liblzma library directory],
+    [with_lzma_libraries="$withval"],[with_lzma_libraries="no"])
+
+AM_CONDITIONAL(HAVE_LZMA, test "x$enable_lzma" = "xyes")
+if test "x$enable_lzma" = "xyes"; then
+
+    if test "x$with_lzma_includes" != "xno"; then
+        CPPFLAGS="${CPPFLAGS} -I${with_lzma_includes}"
+        LZMA_HEADERS="yes"
+    else
+        AC_CHECK_HEADERS(lzma.h, LZMA_HEADERS="yes", LZMA_HEADERS="no")
+    fi
+    
+    if test "x$with_lzma_libraries" != "xno"; then
+        LDFLAGS="${LDFLAGS} -L${with_lzma_libraries}"
+        LZMA_LIB="yes"
+    else
+        AC_CHECK_LIB(lzma, lzma_stream_decoder, LZMA_LIB="yes", LZMA_LIB="no")
     fi
 
-    Z_LIB=""
-    AC_CHECK_LIB(z, inflate,, Z_LIB="no")
-    if test "x$Z_LIB" = "xno"; then
-        echo
-        echo "   ERROR!  zlib library not found, go get it from"
-        echo "   http://www.zlib.net"
-        exit
+    if test "x$LZMA_LIB" != "xno"; then
+        if test "x$LZMA_HEADERS" != "xno"; then
+            CPPFLAGS="$CPPFLAGS -DLZMA"
+            LIBS="$LIBS -llzma"
+        fi
     fi
-    CPPFLAGS="$CPPFLAGS -DZLIB"
-    LIBS="$LIBS -lz"
 fi
 
 AC_ARG_ENABLE(gre,
@@ -1115,47 +1194,11 @@ fi
 
 AM_CONDITIONAL(HAVE_SHARED_REP, test "x$enable_shared_rep" = "xyes")
 
-AC_ARG_ENABLE(rzb-saac,
-[  --enable-rzb-saac        Enable Razorback SaaC support],
-       enable_rzb_saac="$enableval", enable_rzb_saac="no")
-      
-AC_ARG_WITH(librzb_api,
-	[  --with-librzb-api=DIR    librazorback_api directory],
-	[with_librzb_api="$withval"],[with_librzb_api="no"])
-
-if test "x$with_librzb_api" = "xno"; then
-    export PKG_CONFIG_PATH=$prefix/lib/pkgconfig:$PKG_CONFIG_PATH
-else
-    export PKG_CONFIG_PATH=$with_librzb_api/lib/pkgconfig:$PKG_CONFIG_PATH
-fi
-
-# Define PKG_CHECK_MODULES if it doesnt already exist. 
+# Define PKG_CHECK_MODULES if it doesnt already exist.
 #file_ This prevents './configure' from erroring on machines that dont have
 # 'pkgconfig' installed.
-m4_ifdef([PKG_CHECK_MODULES],[], [m4_define([PKG_CHECK_MODULES], 
-     [echo "PKG_CHECK_MODULES not defined"])])
-
-if test "x$enable_rzb_saac" = "xyes"; then
-    AC_CHECK_PROG(PKG_CONFIG,pkg-config,yes)
-    if test "x$PKG_CONFIG" != "xyes"; then
-        echo
-        echo
-        echo "   ERROR!  pkg-config not found, go get it from"
-        echo "   http://freedesktop.org"
-        exit
-    fi
-
-    PKG_CHECK_MODULES([RAZORBACK], [razorback >= 0.1.3], [], [LRZB=no])
-    if test "x$LRZB" = "xno"; then
-        echo
-        echo "   ERROR!  razorback_api library not found, go get it from"
-        echo "   http://sourceforge.net/projects/razorbacktm/"
-        exit
-    fi
-fi
-
-AM_CONDITIONAL([WANT_SF_SAAC], [test x$enable_rzb_saac = xyes])
-
+#m4_ifdef([PKG_CHECK_MODULES],[], [m4_define([PKG_CHECK_MODULES], 
+#     [echo "PKG_CHECK_MODULES not defined"])])
 
 AC_ARG_ENABLE(large-pcap,
 [  --enable-large-pcap      Enable support for pcaps larger than 2 GB],
@@ -1177,6 +1220,46 @@ AS_IF([test x$enable_file_inspect = xyes],
     [AC_DEFINE([FEAT_FILE_INSPECT],[1],[Build with extended file inspection features. (Experimental)]) ])
 AM_CONDITIONAL([FEAT_FILE_INSPECT],[test x$enable_file_inspect = xyes])
 
+export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
+
+###### Start OpenAppId
+AC_ARG_ENABLE([open-appid],
+    [AS_HELP_STRING([--enable-open-appid ],[Build with application id support. (Experimental)])],
+    [enable_open_appid=$enableval],[enable_open_appid=no])
+
+AM_CONDITIONAL([FEAT_OPEN_APPID],[test x$enable_open_appid = xyes])
+
+if test "x$enable_open_appid" = "xyes"; then
+    AC_DEFINE([FEAT_OPEN_APPID],[1],[Build with application id support. (Experimental)])
+    CONFIGFLAGS="$CONFIGFLAGS -DFEAT_OPEN_APPID"
+
+    PKG_CHECK_MODULES(luajit, luajit,LLUAJIT="yes",LLUAJIT="no")
+    if test "x$LLUAJIT" = "xyes"; then
+        CONFIGFLAGS="$CONFIGFLAGS -DHAVE_LIBLUAJIT"
+        LUA_CFLAGS="$luajit_CFLAGS"
+        LUA_LIBS="$luajit_LIBS"
+        AC_SUBST(LUA_CFLAGS)
+        AC_SUBST(LUA_LIBS)
+        if test "x$macos" != "xno"; then
+            LDFLAGS="${LDFLAGS} -pagezero_size 10000 -image_base 100000000"
+        fi
+
+    else
+        echo
+        echo "   ERROR!  LuaJIT library not found. For better performance, go get it from"
+        echo "   http://www.luajit.org/."
+        AC_MSG_ERROR("Fatal!")
+    fi
+
+    AC_CHECK_HEADER(openssl/x509.h, [AC_CHECK_LIB(crypto, d2i_X509, openssl_x509=yes, openssl_x509=no)],openssl_x509=no)
+    if test "x$openssl_x509" = "xno"; then
+        echo
+        echo "   ERROR!  openssl/x509.h or openssl library not found." 
+        AC_MSG_ERROR("Fatal!")
+    fi
+fi
+
+###### End OpenAppId
 # let's make some fixes..
 
 CFLAGS="${CFLAGS} ${CCONFIGFLAGS}"
@@ -1276,7 +1359,7 @@ fi
 echo $CFLAGS > cflags.out
 echo $CPPFLAGS > cppflags.out
 
-INCLUDES='-I$(top_srcdir) -I$(top_srcdir)/src -I$(top_srcdir)/src/sfutil $(extra_incl) -I$(top_srcdir)/src/output-plugins -I$(top_srcdir)/src/detection-plugins -I$(top_srcdir)/src/dynamic-plugins -I$(top_srcdir)/src/preprocessors -I$(top_srcdir)/src/preprocessors/portscan -I$(top_srcdir)/src/preprocessors/HttpInspect/include -I$(top_srcdir)/src/preprocessors/Stream5 -I$(top_srcdir)/src/target-based -I$(top_srcdir)/src/control -I$(top_srcdir)/src/file-process -I$(top_srcdir)/src/file-process/libs -I$(top_srcdir)/src/side-channel -I$(top_srcdir)/src/side-channel/plugins'
+INCLUDES='-I$(top_srcdir) -I$(top_srcdir)/src -I$(top_srcdir)/src/sfutil $(extra_incl) -I$(top_srcdir)/src/output-plugins -I$(top_srcdir)/src/detection-plugins -I$(top_srcdir)/src/dynamic-plugins -I$(top_srcdir)/src/preprocessors -I$(top_srcdir)/src/preprocessors/portscan -I$(top_srcdir)/src/preprocessors/HttpInspect/include -I$(top_srcdir)/src/preprocessors/Session -I$(top_srcdir)/src/preprocessors/Stream6 -I$(top_srcdir)/src/target-based -I$(top_srcdir)/src/control -I$(top_srcdir)/src/file-process -I$(top_srcdir)/src/file-process/libs -I$(top_srcdir)/src/side-channel -I$(top_srcdir)/src/side-channel/plugins'
 
 AC_SUBST(INCLUDES)
 AC_SUBST(CONFIGFLAGS)
@@ -1321,8 +1404,8 @@ src/dynamic-preprocessors/dns/Makefile   \
 src/dynamic-preprocessors/ssl/Makefile   \
 src/dynamic-preprocessors/modbus/Makefile   \
 src/dynamic-preprocessors/dnp3/Makefile   \
-src/dynamic-preprocessors/rzb_saac/Makefile   \
 src/dynamic-preprocessors/file/Makefile   \
+src/dynamic-preprocessors/appid/Makefile   \
 src/dynamic-output/Makefile   \
 src/dynamic-output/plugins/Makefile   \
 src/dynamic-output/libs/Makefile   \
@@ -1334,13 +1417,15 @@ src/preprocessors/HttpInspect/include/Makefile    \
 src/preprocessors/HttpInspect/utils/Makefile \
 src/preprocessors/HttpInspect/anomaly_detection/Makefile \
 src/preprocessors/HttpInspect/client/Makefile \
+src/preprocessors/HttpInspect/files/Makefile \
 src/preprocessors/HttpInspect/event_output/Makefile \
 src/preprocessors/HttpInspect/mode_inspection/Makefile \
 src/preprocessors/HttpInspect/normalization/Makefile \
 src/preprocessors/HttpInspect/server/Makefile \
 src/preprocessors/HttpInspect/session_inspection/Makefile \
 src/preprocessors/HttpInspect/user_interface/Makefile \
-src/preprocessors/Stream5/Makefile \
+src/preprocessors/Session/Makefile \
+src/preprocessors/Stream6/Makefile \
 src/parser/Makefile \
 src/target-based/Makefile \
 doc/Makefile \
@@ -1353,6 +1438,8 @@ tools/Makefile \
 tools/control/Makefile \
 tools/u2boat/Makefile \
 tools/u2spewfoo/Makefile \
+tools/u2openappid/Makefile \
+tools/u2streamer/Makefile \
 tools/file_server/Makefile \
 src/win32/Makefile])
 AC_OUTPUT
